### ISSUE TITLE
ML.NET Hackathon Idea Probably something gaming-related

### ISSUE THREAD

**Issue by frankhaugen** [virtualmlnet/hackathon-2020#8]
## Hackathon Idea
We want to do something with gaming, maybe integrating it with OpenRA or ManagedDoom, (Classic games implemented in C#). There is still an on-going discussion on the details, so I might change the details at a later time.

### Your name
Frank, (Dev)
Frank's Cohabitating Girlfriend, (Junior dev, and team lead)
Frank and his GF's Drinking Buddy, (Dev)
Frank and his GF's Other Drinking Buddy, (Senior-ish dev)
(Names will be added when I get a written consent; GDPR)

### Team name
Omega Force

We are 3 .net-devs, one Kotlin dev and beer!

### Brief Description
In a game like Red Alert, (or Open RA), there should be the possibility for introducing machine learning, and there are very few examples online of using ML.net for gaming-related stuff. Maybe a neural network to kill it in OpenRA's multiplayer? Or perhaps create a learning AI that uses the multiplayer matches' data to base a game AI on, that can be merged into the actual game. Or maybe we create a casino-game like blackjack with a dealer and 5 AI's all battling it out. Who knows. We will overcome and adapt!

### Other
**Are you looking for team members?**
- [ ] Yes
- [ ] No
- [X] If someone are being left out, and is a good personality-fit, we'll take them 😺 

**Would you like to have a mentor assigned to your team?**
- [X] Yes
- [ ] No

**Comment by jernejk** [comment]
Very curious, I would love to keep a close eye on this project. 😊
Genetic Algorithms with ML.NET to combine exploratory algorithm with ML?
https://github.com/lhalsey/BlazorAI

In essence, you use a Genetic Algorithm to figure out what could be a good strategy via brute and ML.NET that learns from those brute force attempts to find patterns. Kinda patching up the weakness of each other.

Genetic Algorithms don't look for patterns per se, they just brute force different things and try to stick with what works.
ML.NET could look at the results and perhaps find patterns of why it was successful (or at least symptoms of success), which in theory would be better than the Genetic Algorithm which blindly followed a fitness function toward a better score.

**Comment by frankhaugen** [comment]
We are here to have mostly fun and hopefully learn something! :-D

**Comment by frankhaugen** [comment]
After so much issues getting a model trained, and most of the team having other real-life concerns popping up, there is nothing worth posting an entry about, (nor do I have time to make a video).

There is no time to retrain the model, but the closest I've gotten, is this:
![image](https://user-images.githubusercontent.com/13543585/99627535-c9f6e900-2a34-11eb-920f-cccd97ba47b1.png)
(The model is trained to identify power-ups and enemies, and it detects them, but all the regions are drawn on more or less the same area, so it needs a lot of re-training)

Thanks to @briacht and @luisquintanilla for assisting with answering some basic technical questions, (that helped a lot)

The next time, (and please let there be more hackathons), I'll actually done some research beforehand, and not just look at @jwood803 's excellent videos: [https://www.youtube.com/playlist?list=PLl_upHIj19Zy3o09oICOutbNfXj332czx](https://www.youtube.com/playlist?list=PLl_upHIj19Zy3o09oICOutbNfXj332czx)

My team might have collapsed, but for my part, I've been motivated to really learn this stuff. I might work AI/ML-adjacent in my day-job, but I'm a complete noob on the AI/ML -topic, and I want that to change, so I will spend some time the next couple of months getting into more ML.net.

I once read that the best way to learn something is to teach it to others, so I think I'll do just that by creating some tutorials on youtube to summarize what has been learned

**Comment by luisquintanilla** [comment]
@frankhaugen 5 days is a short time, definitely gotta give yourself and the team more credit for what you've done here! Happy to hear you're motivated to continue your AI / ML learning journey. We're always around and happy to help. I'm sure we'll see you around and look forward to your next hackathon project! 😉
